language: java
jdk:
- openjdk7
- oraclejdk7
install: true
script: "./gradlew build --info"
before_install:
- export JAVA7_HOME=$(jdk_switcher home jdk7)
after_success:
- "./gradlew travisRelease"
after_failure:
- "./gradlew build --stacktrace --debug"
env:
  global:
    secure: g6VTS4WjMmuT0erHn6VVdz21XQM9ix7u20+FgpkphL3IjEBkpLQr5bQTGXc8N2ORuV5Lw9ANh77jGG3MutA6gOw7EEolTeZOGzAFOiSu7QjbgBoUy2Xyb/FLNWmByFWgqSx8fH8CmiR5nNVmjco9BxrInSz7tNbMhVPWw7pj8zg=
sudo: false
cache:
  directories:
  - $HOME/.gradle/caches
